language: node_js
node_js: stable

sudo: required

branches:
  only:
    - main
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - npm install
  - npm run deploy
